//// <auto-generated />
//using System;
//using Hospital.DAL;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace Hospital.DAL.Migrations
//{
//    [DbContext(typeof(HopitalContext))]
//    [Migration("20231119122253_addDises")]
//    partial class addDises
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "7.0.13")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("Hospital.DAL.AddOnApplicationUser", b =>
//                {
//                    b.Property<string>("Id")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<int>("AccessFailedCount")
//                        .HasColumnType("int");

//                    b.Property<string>("ConcurrencyStamp")
//                        .IsConcurrencyToken()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Email")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<bool>("EmailConfirmed")
//                        .HasColumnType("bit");

//                    b.Property<string>("FirstName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("LastName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("LockoutEnabled")
//                        .HasColumnType("bit");

//                    b.Property<DateTimeOffset?>("LockoutEnd")
//                        .HasColumnType("datetimeoffset");

//                    b.Property<string>("NormalizedEmail")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<string>("NormalizedUserName")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<string>("PasswordHash")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("PhoneNumber")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("PhoneNumberConfirmed")
//                        .HasColumnType("bit");

//                    b.Property<string>("SecurityStamp")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("TwoFactorEnabled")
//                        .HasColumnType("bit");

//                    b.Property<string>("UserName")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<DateTime>("birthDate")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("gender")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.HasIndex("NormalizedEmail")
//                        .HasDatabaseName("EmailIndex");

//                    b.HasIndex("NormalizedUserName")
//                        .IsUnique()
//                        .HasDatabaseName("UserNameIndex")
//                        .HasFilter("[NormalizedUserName] IS NOT NULL");

//                    b.ToTable("AspNetUsers", (string)null);
//                });

//            modelBuilder.Entity("Hospital.DAL.Booking", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<DateTime>("DateOfBook")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("DoctorId")
//                        .HasColumnType("int");

//                    b.Property<string>("Email")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("PatName")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("PatSubmitDate")
//                        .HasColumnType("datetime2");

//                    b.Property<TimeSpan>("PatSubmitTime")
//                        .HasColumnType("time");

//                    b.Property<TimeSpan>("TimeOfBook")
//                        .HasColumnType("time");

//                    b.Property<int>("number")
//                        .HasColumnType("int");

//                    b.Property<int>("patId")
//                        .HasColumnType("int");

//                    b.Property<string>("patientid")
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("Id");

//                    b.HasIndex("DoctorId");

//                    b.HasIndex("patientid");

//                    b.ToTable("Bookings");
//                });

//            modelBuilder.Entity("Hospital.DAL.Department", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("Description")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("HosptialID")
//                        .HasColumnType("int");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("deptImage")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.HasIndex("HosptialID");

//                    b.ToTable("Department");

//                    b.HasData(
//                        new
//                        {
//                            Id = 1,
//                            Description = "The cardiology department specializes in the diagnosis and treatment of heart diseases and conditions.",
//                            HosptialID = 1,
//                            Name = "Cardiology",
//                            deptImage = "https://www.centrecardiolaval.com/wp-content/uploads/2023/07/medical-concept-with-heart-and-electrocardiogram-r-2021-08-31-15-58-51-utc-1536x1024.jpg"
//                        },
//                        new
//                        {
//                            Id = 2,
//                            Description = "The neurology department specializes in the diagnosis and treatment of diseases and conditions of the brain, spinal cord, and peripheral nerves.",
//                            HosptialID = 1,
//                            Name = "Neurology",
//                            deptImage = "https://muthumeenakshihospitals.com/img/Neurology-and-Neurosurgery.png"
//                        },
//                        new
//                        {
//                            Id = 3,
//                            Description = "The orthopedics department specializes in the diagnosis and treatment of diseases and conditions of the musculoskeletal system, including bones, joints, muscles, and ligaments.",
//                            HosptialID = 1,
//                            Name = "Orthopedics",
//                            deptImage = "https://sayaamed.com/wp-content/uploads/2022/01/Orthopedics-in-sayaa-med-1.jpg"
//                        },
//                        new
//                        {
//                            Id = 4,
//                            Description = "The pediatrics department specializes in the diagnosis and treatment of diseases and conditions of children from birth to adolescence.",
//                            HosptialID = 1,
//                            Name = "Pediatrics",
//                            deptImage = "https://wakeforestpediatrics.com/wp-content/uploads/2020/10/Choosing-a-Pediatrician.jpeg"
//                        },
//                        new
//                        {
//                            Id = 5,
//                            Description = "The surgery department specializes in the diagnosis and treatment of diseases and conditions that require surgical intervention.",
//                            HosptialID = 1,
//                            Name = "Surgery",
//                            deptImage = "https://i0.wp.com/post.medicalnewstoday.com/wp-content/uploads/sites/3/2023/03/cosmetic_surgery_GettyImages1313477062_Header-1024x575.jpg?w=1155&h=1528"
//                        },
//                        new
//                        {
//                            Id = 6,
//                            Description = "The cardiology department specializes in the diagnosis and treatment of heart diseases and conditions.",
//                            HosptialID = 2,
//                            Name = "Cardiology",
//                            deptImage = "https://www.centrecardiolaval.com/wp-content/uploads/2023/07/medical-concept-with-heart-and-electrocardiogram-r-2021-08-31-15-58-51-utc-1536x1024.jpg"
//                        },
//                        new
//                        {
//                            Id = 7,
//                            Description = "The neurology department specializes in the diagnosis and treatment of diseases and conditions of the brain, spinal cord, and peripheral nerves.",
//                            HosptialID = 2,
//                            Name = "Neurology",
//                            deptImage = "https://muthumeenakshihospitals.com/img/Neurology-and-Neurosurgery.png"
//                        },
//                        new
//                        {
//                            Id = 8,
//                            Description = "The orthopedics department specializes in the diagnosis and treatment of diseases and conditions of the musculoskeletal system, including bones, joints, muscles, and ligaments.",
//                            HosptialID = 2,
//                            Name = "Orthopedics",
//                            deptImage = "https://sayaamed.com/wp-content/uploads/2022/01/Orthopedics-in-sayaa-med-1.jpg"
//                        },
//                        new
//                        {
//                            Id = 9,
//                            Description = "The pediatrics department specializes in the diagnosis and treatment of diseases and conditions of children from birth to adolescence.",
//                            HosptialID = 2,
//                            Name = "Pediatrics",
//                            deptImage = "https://wakeforestpediatrics.com/wp-content/uploads/2020/10/Choosing-a-Pediatrician.jpeg"
//                        },
//                        new
//                        {
//                            Id = 10,
//                            Description = "The surgery department specializes in the diagnosis and treatment of diseases and conditions that require surgical intervention.",
//                            HosptialID = 2,
//                            Name = "Surgery",
//                            deptImage = "https://i0.wp.com/post.medicalnewstoday.com/wp-content/uploads/sites/3/2023/03/cosmetic_surgery_GettyImages1313477062_Header-1024x575.jpg?w=1155&h=1528"
//                        });
//                });

//            modelBuilder.Entity("Hospital.DAL.Disease", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("Patientid")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<int>("PatientsID")
//                        .HasColumnType("int");

//                    b.Property<string>("UserId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("diseaseDetails")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("diseaseName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("diseasetreatment")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("doctorName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("patientName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.HasIndex("Patientid");

//                    b.HasIndex("UserId")
//                        .IsUnique();

//                    b.ToTable("Disease");
//                });

//            modelBuilder.Entity("Hospital.DAL.Doctor", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<int>("DepartmentID")
//                        .HasColumnType("int");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ProfilePic")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("description")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("price")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("DepartmentID");

//                    b.ToTable("Doctor");

//                    b.HasData(
//                        new
//                        {
//                            Id = 1,
//                            DepartmentID = 1,
//                            Name = "ahmed",
//                            ProfilePic = "https://yt3.googleusercontent.com/ytc/APkrFKYQtHv2GYhbAQkrTRknWk6YVrDLLZk1YovsUcT0Aw=s900-c-k-c0x00ffffff-no-rj",
//                            description = "sfddasdadsadasasdsad",
//                            price = 200
//                        },
//                        new
//                        {
//                            Id = 2,
//                            DepartmentID = 2,
//                            Name = "helmy",
//                            ProfilePic = "https://yt3.googleusercontent.com/ytc/APkrFKYQtHv2GYhbAQkrTRknWk6YVrDLLZk1YovsUcT0Aw=s900-c-k-c0x00ffffff-no-rj",
//                            description = "sfddasdadsadasasdsad",
//                            price = 250
//                        },
//                        new
//                        {
//                            Id = 3,
//                            DepartmentID = 3,
//                            Name = "abdallah",
//                            ProfilePic = "https://yt3.googleusercontent.com/ytc/APkrFKYQtHv2GYhbAQkrTRknWk6YVrDLLZk1YovsUcT0Aw=s900-c-k-c0x00ffffff-no-rj",
//                            description = "sfddasdadsadasasdsad",
//                            price = 300
//                        },
//                        new
//                        {
//                            Id = 4,
//                            DepartmentID = 4,
//                            Name = "mustafa",
//                            ProfilePic = "https://yt3.googleusercontent.com/ytc/APkrFKYQtHv2GYhbAQkrTRknWk6YVrDLLZk1YovsUcT0Aw=s900-c-k-c0x00ffffff-no-rj",
//                            description = "sfddasdadsadasasdsad",
//                            price = 190
//                        },
//                        new
//                        {
//                            Id = 5,
//                            DepartmentID = 5,
//                            Name = "mustafa",
//                            ProfilePic = "https://yt3.googleusercontent.com/ytc/APkrFKYQtHv2GYhbAQkrTRknWk6YVrDLLZk1YovsUcT0Aw=s900-c-k-c0x00ffffff-no-rj",
//                            description = "sfddasdadsadasasdsad",
//                            price = 230
//                        },
//                        new
//                        {
//                            Id = 6,
//                            DepartmentID = 6,
//                            Name = "ahmed",
//                            ProfilePic = "https://yt3.googleusercontent.com/ytc/APkrFKYQtHv2GYhbAQkrTRknWk6YVrDLLZk1YovsUcT0Aw=s900-c-k-c0x00ffffff-no-rj",
//                            description = "sfddasdadsadasasdsad",
//                            price = 350
//                        },
//                        new
//                        {
//                            Id = 7,
//                            DepartmentID = 7,
//                            Name = "helmy",
//                            ProfilePic = "https://yt3.googleusercontent.com/ytc/APkrFKYQtHv2GYhbAQkrTRknWk6YVrDLLZk1YovsUcT0Aw=s900-c-k-c0x00ffffff-no-rj",
//                            description = "sfddasdadsadasasdsad",
//                            price = 200
//                        },
//                        new
//                        {
//                            Id = 8,
//                            DepartmentID = 8,
//                            Name = "abdallah",
//                            ProfilePic = "https://yt3.googleusercontent.com/ytc/APkrFKYQtHv2GYhbAQkrTRknWk6YVrDLLZk1YovsUcT0Aw=s900-c-k-c0x00ffffff-no-rj",
//                            description = "sfddasdadsadasasdsad",
//                            price = 220
//                        },
//                        new
//                        {
//                            Id = 9,
//                            DepartmentID = 9,
//                            Name = "mustafa",
//                            ProfilePic = "https://yt3.googleusercontent.com/ytc/APkrFKYQtHv2GYhbAQkrTRknWk6YVrDLLZk1YovsUcT0Aw=s900-c-k-c0x00ffffff-no-rj    ",
//                            description = "sfddasdadsadasasdsad",
//                            price = 320
//                        },
//                        new
//                        {
//                            Id = 10,
//                            DepartmentID = 10,
//                            Name = "mustafa",
//                            ProfilePic = "https://yt3.googleusercontent.com/ytc/APkrFKYQtHv2GYhbAQkrTRknWk6YVrDLLZk1YovsUcT0Aw=s900-c-k-c0x00ffffff-no-rj",
//                            description = "sfddasdadsadasasdsad",
//                            price = 300
//                        });
//                });

//            modelBuilder.Entity("Hospital.DAL.Hosptial", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("Address")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Hosptial");

//                    b.HasData(
//                        new
//                        {
//                            Id = 1,
//                            Address = "Alex",
//                            Name = "Alex"
//                        },
//                        new
//                        {
//                            Id = 2,
//                            Address = "Cairo",
//                            Name = "Cairo"
//                        });
//                });

//            modelBuilder.Entity("Hospital.DAL.Patient", b =>
//                {
//                    b.Property<string>("id")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("address")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("birthDate")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("email")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("name")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("number")
//                        .HasColumnType("int");

//                    b.HasKey("id");

//                    b.ToTable("patients");
//                });

//            modelBuilder.Entity("Hospital.DAL.WorkSchedule", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<int>("DayOfWeek")
//                        .HasColumnType("int");

//                    b.Property<int>("DoctorId")
//                        .HasColumnType("int");

//                    b.Property<TimeSpan>("EndTime")
//                        .HasColumnType("time");

//                    b.Property<TimeSpan>("StartTime")
//                        .HasColumnType("time");

//                    b.HasKey("Id");

//                    b.HasIndex("DoctorId");

//                    b.ToTable("WorkSchedules");

//                    b.HasData(
//                        new
//                        {
//                            Id = 1,
//                            DayOfWeek = 0,
//                            DoctorId = 1,
//                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 2,
//                            DayOfWeek = 2,
//                            DoctorId = 1,
//                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 3,
//                            DayOfWeek = 3,
//                            DoctorId = 1,
//                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 4,
//                            DayOfWeek = 4,
//                            DoctorId = 2,
//                            EndTime = new TimeSpan(0, 19, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 5,
//                            DayOfWeek = 5,
//                            DoctorId = 2,
//                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 6,
//                            DayOfWeek = 1,
//                            DoctorId = 3,
//                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 7,
//                            DayOfWeek = 4,
//                            DoctorId = 3,
//                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 8,
//                            DayOfWeek = 6,
//                            DoctorId = 3,
//                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 9,
//                            DayOfWeek = 6,
//                            DoctorId = 4,
//                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 10,
//                            DayOfWeek = 1,
//                            DoctorId = 4,
//                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 11,
//                            DayOfWeek = 3,
//                            DoctorId = 4,
//                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 12,
//                            DayOfWeek = 5,
//                            DoctorId = 5,
//                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 13,
//                            DayOfWeek = 1,
//                            DoctorId = 5,
//                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 14,
//                            DayOfWeek = 3,
//                            DoctorId = 5,
//                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 15,
//                            DayOfWeek = 6,
//                            DoctorId = 6,
//                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 16,
//                            DayOfWeek = 1,
//                            DoctorId = 6,
//                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 17,
//                            DayOfWeek = 4,
//                            DoctorId = 6,
//                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 18,
//                            DayOfWeek = 0,
//                            DoctorId = 7,
//                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 19,
//                            DayOfWeek = 2,
//                            DoctorId = 7,
//                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 20,
//                            DayOfWeek = 4,
//                            DoctorId = 7,
//                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 21,
//                            DayOfWeek = 0,
//                            DoctorId = 8,
//                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 22,
//                            DayOfWeek = 2,
//                            DoctorId = 8,
//                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 23,
//                            DayOfWeek = 5,
//                            DoctorId = 8,
//                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 24,
//                            DayOfWeek = 0,
//                            DoctorId = 9,
//                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 25,
//                            DayOfWeek = 3,
//                            DoctorId = 9,
//                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 26,
//                            DayOfWeek = 5,
//                            DoctorId = 9,
//                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 27,
//                            DayOfWeek = 6,
//                            DoctorId = 10,
//                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 28,
//                            DayOfWeek = 1,
//                            DoctorId = 10,
//                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 29,
//                            DayOfWeek = 3,
//                            DoctorId = 10,
//                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
//                        },
//                        new
//                        {
//                            Id = 30,
//                            DayOfWeek = 1,
//                            DoctorId = 2,
//                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
//                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
//                        });
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
//                {
//                    b.Property<string>("Id")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("ConcurrencyStamp")
//                        .IsConcurrencyToken()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Name")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<string>("NormalizedName")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.HasKey("Id");

//                    b.HasIndex("NormalizedName")
//                        .IsUnique()
//                        .HasDatabaseName("RoleNameIndex")
//                        .HasFilter("[NormalizedName] IS NOT NULL");

//                    b.ToTable("AspNetRoles", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("ClaimType")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ClaimValue")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("RoleId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("Id");

//                    b.HasIndex("RoleId");

//                    b.ToTable("AspNetRoleClaims", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("ClaimType")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ClaimValue")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("UserId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("Id");

//                    b.HasIndex("UserId");

//                    b.ToTable("AspNetUserClaims", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                {
//                    b.Property<string>("LoginProvider")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("ProviderKey")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("UserId")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("ProviderDisplayName")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("LoginProvider", "ProviderKey", "UserId");

//                    b.HasIndex("UserId");

//                    b.ToTable("AspNetUserLogins", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                {
//                    b.Property<string>("UserId")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("RoleId")
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("UserId", "RoleId");

//                    b.HasIndex("RoleId");

//                    b.ToTable("AspNetUserRoles", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                {
//                    b.Property<string>("UserId")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("LoginProvider")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("Name")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("Value")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("UserId", "LoginProvider", "Name");

//                    b.ToTable("AspNetUserTokens", (string)null);
//                });

//            modelBuilder.Entity("Hospital.DAL.Booking", b =>
//                {
//                    b.HasOne("Hospital.DAL.Doctor", "Doctor")
//                        .WithMany("Bookings")
//                        .HasForeignKey("DoctorId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Hospital.DAL.Patient", "patient")
//                        .WithMany("Bookings")
//                        .HasForeignKey("patientid");

//                    b.Navigation("Doctor");

//                    b.Navigation("patient");
//                });

//            modelBuilder.Entity("Hospital.DAL.Department", b =>
//                {
//                    b.HasOne("Hospital.DAL.Hosptial", "Hosptial")
//                        .WithMany("Departments")
//                        .HasForeignKey("HosptialID")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Hosptial");
//                });

//            modelBuilder.Entity("Hospital.DAL.Disease", b =>
//                {
//                    b.HasOne("Hospital.DAL.Patient", "Patient")
//                        .WithMany("Disease")
//                        .HasForeignKey("Patientid");

//                    b.HasOne("Hospital.DAL.AddOnApplicationUser", "AddOnApplicationUser")
//                        .WithOne("Disease")
//                        .HasForeignKey("Hospital.DAL.Disease", "UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("AddOnApplicationUser");

//                    b.Navigation("Patient");
//                });

//            modelBuilder.Entity("Hospital.DAL.Doctor", b =>
//                {
//                    b.HasOne("Hospital.DAL.Department", "Department")
//                        .WithMany("Doctors")
//                        .HasForeignKey("DepartmentID")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Department");
//                });

//            modelBuilder.Entity("Hospital.DAL.WorkSchedule", b =>
//                {
//                    b.HasOne("Hospital.DAL.Doctor", "Doctor")
//                        .WithMany("WorkSchedules")
//                        .HasForeignKey("DoctorId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Doctor");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                        .WithMany()
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                {
//                    b.HasOne("Hospital.DAL.AddOnApplicationUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                {
//                    b.HasOne("Hospital.DAL.AddOnApplicationUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                        .WithMany()
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Hospital.DAL.AddOnApplicationUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                {
//                    b.HasOne("Hospital.DAL.AddOnApplicationUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Hospital.DAL.AddOnApplicationUser", b =>
//                {
//                    b.Navigation("Disease");
//                });

//            modelBuilder.Entity("Hospital.DAL.Department", b =>
//                {
//                    b.Navigation("Doctors");
//                });

//            modelBuilder.Entity("Hospital.DAL.Doctor", b =>
//                {
//                    b.Navigation("Bookings");

//                    b.Navigation("WorkSchedules");
//                });

//            modelBuilder.Entity("Hospital.DAL.Hosptial", b =>
//                {
//                    b.Navigation("Departments");
//                });

//            modelBuilder.Entity("Hospital.DAL.Patient", b =>
//                {
//                    b.Navigation("Bookings");

//                    b.Navigation("Disease");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
